services:

  # convenience services
  checkout.data_manager:
    class: 'Siemendev\Checkout\SymfonyBridge\Data\CheckoutDataManager'
    public: true
    arguments:
      $requestStack: '@request_stack'
  Siemendev\Checkout\SymfonyBridge\Data\CheckoutDataManager:
    alias: 'checkout.data_manager'
    public: false

  checkout.data:
    class: Siemendev\Checkout\Data\CheckoutDataInterface
    public: true
    shared: false
    factory: [ '@checkout.data_manager', 'getCheckoutData' ]
  Siemendev\Checkout\Data\CheckoutDataInterface:
    alias: 'checkout.data'
    public: false
  
  checkout.step_machine:
    public: true
    class: 'Siemendev\Checkout\Step\Machine\StepMachine'
  Siemendev\Checkout\Step\Machine\StepMachineInterface:
    alias: checkout.step_machine
    public: false

  checkout.steps.delivery_address:
    public: false
    class: 'Siemendev\Checkout\Step\Address\Delivery\DeliveryAddressStep'
  checkout.steps.billing_address:
    public: false
    class: 'Siemendev\Checkout\Step\Address\Billing\BillingAddressStep'
  checkout.steps.summary:
    public: false
    class: 'Siemendev\Checkout\Step\Summary\SummaryStep'
  checkout.steps.delivery:
    public: false
    class: 'Siemendev\Checkout\Step\Delivery\DeliveryStep'
