checkout:
  data_creator: Demo\Commerce\Data\CheckoutDataCreator
  steps:
    - Demo\Commerce\Step\CartStep
    - checkout.steps.billing_address
    - checkout.steps.delivery_address
    - Demo\Commerce\Step\AgeVerificationStep
    - checkout.steps.delivery
    - checkout.steps.products_payment
    - checkout.steps.summary

checkout_delivery:
  options:
    - Demo\Commerce\Delivery\DhlDeliveryOption

checkout_gift_card:
  payment_manager: Demo\Commerce\GiftCard\GiftCardPaymentManager
