checkout:
  data_creator: App\Commerce\DataCreator
  steps:
    - App\Commerce\Step\CartStep
    - checkout.steps.billing_address
    - checkout.steps.delivery_address
    - App\Commerce\Step\AgeVerificationStep
    - checkout.steps.delivery
    - checkout.steps.products_payment
    - checkout.steps.summary

checkout_delivery:
  options:
    - App\Commerce\Delivery\DhlDeliveryOption
