checkout:
  data_creator: App\Commerce\Data\CheckoutDataCreator
  steps:
    - App\Commerce\Step\CartStep
    - checkout.steps.billing_address
    - checkout.steps.delivery_address
    - App\Commerce\Step\AgeVerificationStep
    - checkout.steps.delivery
    - checkout.steps.products_payment
    - checkout.steps.summary

checkout_delivery:
  options:
    - App\Commerce\Delivery\DhlDeliveryOption

checkout_gift_card:
  capturing_manager: App\Commerce\GiftCard\GiftCardCapturingManager
