services:

  checkout.payment_methods.gift_card:
    public: true
    autoconfigure: true
    class: Siemendev\Checkout\GiftCard\PaymentMethod\GiftCardPaymentMethod
  Siemendev\Checkout\GiftCard\PaymentMethod\GiftCardPaymentMethodInterface:
    public: false
    alias: checkout.payment_methods.gift_card
