services:

  checkout.steps.products_payment:
    public: true
    class: 'Siemendev\Checkout\Payment\Step\PaymentStep'

  checkout.payment.methods_provider:
    public: true
    class: 'Siemendev\Checkout\Payment\Method\PaymentMethodsProvider'

  Siemendev\Checkout\Payment\Method\PaymentMethodsProviderInterface:
    public: false
    alias: checkout.payment.methods_provider

  checkout.finalization_handlers.payment_capturing:
    public: true
    autoconfigure: true
    class: Siemendev\Checkout\Payment\Finalize\PaymentCapturingFinalizationHandler
    arguments:
      $paymentMethodsProvider: '@checkout.payment.methods_provider'
